# Generated by Django 4.1.5 on 2023-03-27 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='hola@gmail.com', max_length=233, unique=True)),
                ('name', models.CharField(default='', max_length=233, unique=True)),
                ('password', models.CharField(default='', max_length=233)),
                ('cuilt', models.CharField(default='', max_length=233, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('role', models.CharField(default='ROLE_MANAGER', max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=233)),
                ('cuilt', models.CharField(default='', max_length=233, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=233)),
                ('lastNames', models.CharField(default='', max_length=233)),
                ('email', models.EmailField(default='hola@gmail.com', max_length=233, unique=True)),
                ('password', models.CharField(default='', max_length=233)),
                ('isAdmin', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('role', models.CharField(default='ROLE_EMPLOYEE', max_length=233)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('x1', models.FloatField(default=0)),
                ('x2', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('y2', models.FloatField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers')),
            ],
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.CharField(default='', max_length=233)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.bill')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.coordinates')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers'),
        ),
    ]
