# Generated by Django 4.1.4 on 2023-01-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=233)),
                ('coordate_x', models.IntegerField(default=1)),
                ('coordate_y', models.IntegerField(default=1)),
                ('info', models.CharField(default='', max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='hola@gmail.com', max_length=233)),
                ('password', models.CharField(default='', max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=233)),
                ('lastNamess', models.CharField(default='', max_length=233)),
                ('email', models.EmailField(default='hola@gmail.com', max_length=233)),
                ('password', models.CharField(default='', max_length=233)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=233)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies')),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.bill')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.employees'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies'),
        ),
    ]
