# Generated by Django 3.2.12 on 2023-01-29 00:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='cuilt',
            field=models.CharField(default='', max_length=233, unique=True),
        ),
        migrations.AlterField(
            model_name='typedoc',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='coordinateStart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('valueX', models.IntegerField(default=0)),
                ('valueY', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=233, unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers')),
            ],
        ),
        migrations.CreateModel(
            name='coordinateEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('valueX', models.IntegerField(default=0)),
                ('valueY', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=233, unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers')),
            ],
        ),
    ]
