# Generated by Django 4.1.4 on 2023-01-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='provider_config',
        ),
        migrations.AddField(
            model_name='bill',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers'),
        ),
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies'),
        ),
    ]
