# Generated by Django 4.1.4 on 2023-01-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profiel_photo',
        ),
    ]
