# Generated by Django 4.1.5 on 2023-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='name',
            field=models.CharField(default='', max_length=233),
        ),
    ]
