# Generated by Django 4.1.4 on 2023-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='cuilt',
            field=models.CharField(default='', max_length=233),
        ),
    ]
