# Generated by Django 4.1.4 on 2023-03-23 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0002_auto_20230129_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.CharField(default='', max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('x1', models.FloatField(default=0)),
                ('x2', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('y2', models.FloatField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.providers')),
            ],
        ),
        migrations.RemoveField(
            model_name='coordinatestart',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='coordate_x',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='coordate_y',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='info',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='typedoc',
        ),
        migrations.DeleteModel(
            name='coordinateEnd',
        ),
        migrations.DeleteModel(
            name='coordinateStart',
        ),
        migrations.DeleteModel(
            name='TypeDoc',
        ),
        migrations.AddField(
            model_name='billinfo',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.bill'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.coordinates'),
        ),
    ]
