# Generated by Django 4.1.4 on 2023-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0002_companies_cuilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
