# Generated by Django 4.1.4 on 2023-01-09 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0002_alter_bill_id_alter_companies_id_alter_employees_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
