# Generated by Django 4.1.4 on 2023-01-09 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0003_alter_companies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
