# Generated by Django 4.1.4 on 2023-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0004_alter_typedoc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
