# Generated by Django 4.1.4 on 2023-01-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0004_alter_employees_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceContabiliumApp.companies'),
        ),
    ]
