# Generated by Django 4.1.4 on 2023-01-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceContabiliumApp', '0006_rename_lastnamess_employees_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='lastName',
            new_name='lastNamess',
        ),
    ]
